Sintatic changes and fixing static configuration

diff --git a/customize b/customize
--- a/customize
+++ b/customize
@@ -20,28 +20,28 @@
 
 function failure()
 {
-	echo "$@"
-	exit 1
+    echo "$@"
+    exit 1
 }
 
 function prepare_install()
 {
-	cp ${SCRIPT_DIR}/config_files/etc/apt/sources.list /etc/apt
+    cp ${SCRIPT_DIR}/config_files/etc/apt/sources.list /etc/apt
 
-	#try 2 times to avoid slow proxies failures
-	apt-get update || failure "apt-get update failed, error=$?"
+    #try 2 times to avoid slow proxies failures
+    apt-get update || failure "apt-get update failed, error=$?"
 
-	# upstart package is not installed in mini_remix iso so /sbin/initctl is removed by clean_rootfs_after_chroot function.
-	# Make sure /sbin/initctl will be correctly restored after install (see /usr/lib/uck/remaster-live-cd.sh).
-	apt-get install --assume-yes upstart
-	mv /sbin/initctl /sbin/initctl.uck_blocked
-	ln -s /bin/true /sbin/initctl
+    # upstart package is not installed in mini_remix iso so /sbin/initctl is removed by clean_rootfs_after_chroot function.
+    # Make sure /sbin/initctl will be correctly restored after install (see /usr/lib/uck/remaster-live-cd.sh).
+    apt-get install --assume-yes upstart
+    mv /sbin/initctl /sbin/initctl.uck_blocked
+    ln -s /bin/true /sbin/initctl
 }
 
 function finalize_install()
 {
-	apt-get clean
-	apt-get auto-clean
+    apt-get clean
+    apt-get auto-clean
 
     echo '' > /var/log/dpkg.log
     echo '' > /var/log/apt/term.log
@@ -53,12 +53,12 @@ function finalize_install()
 
 function install_packages()
 {
-	apt-get install --assume-yes "$@" || failure "apt-get install $@ failed, error=$?"
+    apt-get install --assume-yes "$@" || failure "apt-get install $@ failed, error=$?"
 }
 
 function remove_packages()
 {
-	apt-get --purge remove --assume-yes "$@" || failure "apt-get remove $@ failed, error=$?"
+    apt-get --purge remove --assume-yes "$@" || failure "apt-get remove $@ failed, error=$?"
 }
 
 SCRIPT_DIR=`dirname "$0"`
@@ -126,8 +126,8 @@ echo '/usr/bin/xhost +' >> /etc/skel/.profile
 favorites=''
 sep=''
 for app in $favorites_launcher ; do
-	favorites="${favorites}${sep}'${app}.desktop'"
-	sep=', '
+    favorites="${favorites}${sep}'${app}.desktop'"
+    sep=', '
 done
 echo -e "[com.canonical.Unity.Launcher]\nfavorites=[${favorites}]" > /usr/share/glib-2.0/schemas/11_com.canonical.Unity.gschema.override
 
@@ -145,11 +145,14 @@ glib-compile-schemas /usr/share/glib-2.0/schemas/
 
 # Coping icones to Desktop
 for app in $favorites_desktop ; do
-        fapp="/usr/share/applications/${app}.desktop"
-        if [ -e "${fapp}" ] ; then
-                cp "${fapp}" /etc/skel/Desktop/
-        fi
+    fapp="/usr/share/applications/${app}.desktop"
+    if [ -e "${fapp}" ] ; then
+        cp "${fapp}" /etc/skel/Desktop/
+    fi
 done
+
+# Allow read access to all for log new files
+sed -i '/FileCreateMode/ s/0640/0644/' /etc/rsyslog.conf
 
 finalize_install
 
